d = {}
name = input("Enter your friend name: ")
lang = input("Enter your friend language: ")
d.update({name: lang})
name = input("Enter your friend name: ")
lang = input("Enter your friend language: ")
d.update({name: lang})
name = input("Enter your friend name: ")
lang = input("Enter your friend language: ")
d.update({name: lang})
name = input("Enter your friend name: ")
lang = input("Enter your friend language: ")
d.update({name: lang})
name = input("Enter your friend name: ")
lang = input("Enter your friend language: ")
d.update({name: lang})
print(d)
